perl get_gene_bed.pl Genes_2k_with_H2A mazie_V4_genes_bed Genes_2k_with_H2A_bed
perl get_gene_bed.pl Genes_2k_with_H3K27 mazie_V4_genes_bed Genes_2k_with_H3K27_bed
perl get_gene_bed.pl Genes_2k_with_both_H2A_H3K27 mazie_V4_genes_bed Genes_2k_with_both_H2A_H3K27_bed
perl get_gene_bed.pl Genes_2k_with_only_H2A mazie_V4_genes_bed Genes_2k_with_only_H2A_bed
perl get_gene_bed.pl Genes_2k_with_only_H3K27 mazie_V4_genes_bed Genes_2k_with_only_H3K27_bed
